pipeline {
  agent any
  stages {
    stage('Checkout') {
      steps {
        git branch: 'main',
            url: 'https://github.com/WinTux/20260716.git',
            credentialsId: 'github-token'
      } 
    }
  }
}
